# Generated by Django 2.2 on 2022-08-08 10:32

import django.core.validators
from django.db import migrations, models
import posts.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'unique': '이미 있는 제목입니다.'}, max_length=100, unique=True)),
                ('content', models.TextField(validators=[django.core.validators.MinLengthValidator(10, '너무 짧습니다. 10자 이상 적어주세요.'), posts.validators.validate_symbols])),
                ('dt_created', models.DateTimeField(auto_now_add=True)),
                ('dt_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
